import banner from "../assets/banner/banner.jpeg";
import { Helmet } from "react-helmet";
import { useLocation } from "react-router-dom";

const Terms = () => {
  const location = useLocation();

  return (
    <div className="bg-[#020617] text-gray-200 min-h-screen pb-20">

      {/* ✅ SEO (UPDATED + STABLE) */}
      <Helmet key={location.pathname}>
        <title>Terms & Conditions - Velvyana</title>

        <meta
          name="description"
          content="Read Velvyana terms and conditions for using our website, services, and policies."
        />

        <meta
          name="keywords"
          content="terms and conditions, velvyana terms, website policy, user agreement"
        />

        <meta name="robots" content="index, follow" />
      </Helmet>

      {/* HERO SECTION */}
      <div className="relative h-[300px] md:h-[400px] w-full">
        <img
          src={banner}
          alt="terms"
          className="w-full h-full object-cover"
        />

        <div className="absolute inset-0 bg-black/60"></div>

        <div className="absolute inset-0 flex items-center justify-center">
          <h1 className="text-white text-3xl md:text-5xl font-light tracking-widest text-center">
            TERMS & CONDITIONS
          </h1>
        </div>
      </div>

      {/* CONTAINER */}
      <div className="relative -mt-16 px-4 flex justify-center">

        <div className="max-w-4xl w-full bg-[#0f172a] rounded-2xl p-6 md:p-10 shadow-xl border border-gray-800 text-gray-300 leading-relaxed text-sm md:text-base">

          <p>
            This document is an electronic record in terms of the Information Technology Act, 2000 and rules there under as applicable. This electronic record is generated by a computer system and does not require any physical or digital signatures.
          </p>

          <p className="mt-4">
            This document is published in accordance with Rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011 that require publishing the rules, regulations, privacy policy and Terms of Use for access or usage of the website{" "}
            <span className="text-white">https://velvyana.com/</span>.
          </p>

          <p className="mt-4">
            The Platform is owned by{" "}
            <span className="text-white font-medium">VELVYANA</span>, with its registered office in Lucknow, Uttar Pradesh, India.
          </p>

          <p className="mt-4">
            By accessing, browsing, or using this Platform, you agree to be bound by these Terms of Use. If you do not agree, please do not use the website.
          </p>

          {/* SECTION */}
          <div className="mt-6">
            <h2 className="text-white text-lg font-semibold mb-2">
              User Responsibilities
            </h2>
            <p>
              You agree to provide accurate information and maintain the confidentiality of your account. You are responsible for all activities that occur under your account.
            </p>
          </div>

          {/* SECTION */}
          <div className="mt-6">
            <h2 className="text-white text-lg font-semibold mb-2">
              Use of Website
            </h2>
            <p>
              You agree not to use the Platform for any unlawful or prohibited activities. Misuse of the website may result in legal action.
            </p>
          </div>

          {/* SECTION */}
          <div className="mt-6">
            <h2 className="text-white text-lg font-semibold mb-2">
              Intellectual Property
            </h2>
            <p>
              All content on this website including design, layout, graphics, and text is owned by Velvyana. Unauthorized use is strictly prohibited.
            </p>
          </div>

          {/* SECTION */}
          <div className="mt-6">
            <h2 className="text-white text-lg font-semibold mb-2">
              Limitation of Liability
            </h2>
            <p>
              We are not liable for any loss or damage arising from the use of this website. Your use of the Platform is at your own risk.
            </p>
          </div>

          {/* SECTION */}
          <div className="mt-6">
            <h2 className="text-white text-lg font-semibold mb-2">
              Governing Law
            </h2>
            <p>
              These terms shall be governed by and interpreted in accordance with the laws of India. Any disputes shall be subject to the jurisdiction of courts in Lucknow, Uttar Pradesh.
            </p>
          </div>

          {/* CONTACT */}
          <div className="mt-6 pt-4 border-t border-gray-800">
            <h2 className="text-white font-semibold mb-2">
              Contact Us
            </h2>

            <p className="text-gray-400">
              For any queries or support, contact:
            </p>

            <p className="text-white mt-2">
              +91 90642 52616
            </p>

            <p className="text-pink-400">
              info@velvyana.com
            </p>
          </div>

        </div>

      </div>

    </div>
  );
};

export default Terms;